### ISSUE TITLE
Re-factor stats to reference the meta objects instead of strings

### ISSUE THREAD

**Issue by tehbeard** [tehbeard/BeardStat#1]
Current IStat implementations store domain, world, category and statistic as strings.

This isn't really useful for being able to parse and filter against. We should move to have the meta objects exist statically (i.e. one object for a WorldMeta, reffed by all stats using it).

Additionally, we will improve the StatMeta, storing the "id" and classifiers (key/value pairs that change the item) alongside formatting information.

We can then lazy-save these properties when stuff is saved
- [x] Implement new StatPointer with classifiers.
- [x] Make other Meta classes follow same pattern for storing one unique instance per property set.
- [x] Migrate IStat to use *Meta Classes
- [x] Update IStat implementations to match
- [ ] Load in block/item/entity data from JSON dump of api.mcjson.com database.
- [x] Rebuild IStatDataProviders to lazy save these properties on saving of an EntityStatBlob
- [ ] Write migration script to update old data to new format (need to look at mapping of old bukkit names to mojang structure) (optional)
